blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
       path('', views.blog_page, name='blog_view'),
       path('single-blog/<slug:slug>', views.single_blog, name='single-blog'),
       path('send-blog-comment/',views.send_blog_comment,name='send_blog_comment')
]

digibazar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('contact/',include('contact.urls')),
    path('product/',include('product.urls')),
    path('account/',include('account.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('cat/', include('category.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('search/',include('search.urls')),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views 

app_name = 'product'


urlpatterns = [
    path('',views.products,name='products_page'),
    path('filter/',views.product_filter,name='product_filter_page'),
    path('filter_result/',views.filter_result, name='filter_result_page'),
    path('<slug:slug>/',views.single_product,name='single_product_page'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('',views.search_product,name='search'),
    path('live_search/',views.live_search,name='live_search')
]

search/views.py
from django.shortcuts import render
from product.models import Product
from django.http import JsonResponse
from django.core.serializers import serialize
import json

# Create your views here.
def search_product(request):
    if request.method == 'POST':
        search_result = Product.objects.filter(title__icontains=request.POST.get('search_keyword'))
        return render(request,'shared/base.html',{'result':search_result})
    else:
        return render(request,'shared/base.html')


def live_search(request):
    data = json.loads(request.body)
    if len(data.get('search_keyword')) > 0:
        search_result = Product.objects.filter(title__icontains=data.get('search_keyword'))
        myjson = json.loads(serialize('json',search_result))
        # print(myjson)
        return JsonResponse({'data':myjson})
    

search/templates/search/result.html
{% extends 'shared/base.html' %}
{% load humanize %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="col-12 px-res-0">
    <div class="product-carousel carousel-md owl-carousel owl-theme">
        {% for product in products %}
        <div class="item">
            <div class="product-card">
                <div class="product-head">
                </div>
                <a class="product-thumb" href="shop-single.html">
                    {% if product.main_picture %}
                        <img src="{{product.main_picture.url}}" alt="Product Thumbnail">
                    {% else %}
                        <img src="/static/img/products/07.jpg" alt="Product Thumbnail">
                    {% endif %}
                </a>
                <div class="product-card-body">
                    <h5 class="product-title ">
                        <a href="shop-single.html" class="align-self-center">{{ product.title }}</a>
                    </h5>
                    <div class="row">
                        <a href="{% url 'product:single_product_page' slug=product.slug %}" class="btn btn-danger col align-self-end">مشاهده محصول</a>
                        <h5 class="product-price col align-self-start">{{product.price|intcomma}} تومان</h5>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <h1>هنوز محصولی در فروشگاه وجود ندارد</h1>
        {% endfor %}

    </div>
</div>

{% endblock %}

search/templates/search/search.html
<html>

<head></head>

<body>
    <h1>this is search page</h1>
    <form action="{% url 'search:search' %}" method="post">
        {% csrf_token %}    
        <input type="text" name="search_keyword" id="search_box"  autocomplete="off">
        <input type="submit">
    </form>
    <ul id="search_results">
        {% for item in result %}
        <div>
            <li style="display: inline;">{{item.title}} {{item.price}}</li>
            <img src="{{item.main_picture.url}}" style="width: 3%; height: 5%; border-radius: 30%; margin-top: 1%;">
        </div>
        {% endfor%}
    </ul>
    <script src="/static/js/search.js"></script>
</body>

</html>