blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
       path('', views.blog_page, name='blog_view'),
       path('single-blog/<slug:slug>', views.single_blog, name='single-blog'),
       path('send-blog-comment/',views.send_blog_comment,name='send_blog_comment')
]

digibazar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('contact/',include('contact.urls')),
    path('product/',include('product.urls')),
    path('account/',include('account.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('cat/', include('category.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('search/',include('search.urls')),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from account.models import User
from ckeditor.fields import RichTextField
# Create your models here.
class Publisher(models.Model):
    title = models.CharField(max_length=100)
    year = models.DateField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    def __str__(self) -> str:
        return self.title

class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = RichTextField(blank=type,null=True)
    publisher = models.ForeignKey(Publisher,on_delete=models.SET_NULL,null=True,blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    main_text = models.TextField()
    img = models.ImageField(upload_to='blog.image', null=True, blank=True)
    date = models.DateField()
    slug = models.SlugField(max_length=100)

    def __str__(self) -> str:
        return self.title
    

class BlogComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_blogcomment_set')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_blogcomment_set')
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    like = models.ManyToManyField(User,related_name='like_blogcomment_set',blank=True)
    dislike = models.ManyToManyField(User,related_name='dislike_blogcomment_set',blank=True)
    admin_verify = models.BooleanField(default=False, choices={True:'تایید', False:'رد'})
    parent = models.ForeignKey('BlogComment', null=True, blank=True, related_name='blogcomment_blogcomment_set', on_delete=models.CASCADE)

    def show_likes(self):
        return self.like.all().count()
    
    def show_dislikes(self):
        return self.dislike.all().count()

    class Meta:
        ordering = ['-date']

blog/views.py
from django.shortcuts import render
from .models import Blog,BlogComment
from django.core.paginator import Paginator
import json
from django.http import JsonResponse
# Create your views here.

def blog_page(request):
    data = Blog.objects.all()
    paginator = Paginator(data,5)
    page_number = request.GET.get('page')
    this_page = paginator.get_page(page_number)
    recent_blog = Blog.objects.all().order_by('-id')[:3]
    return render(request, 'blog/blog.html', {'blogs':data, 'recent_blog':recent_blog, 'this_page':this_page, 'paginator':paginator})



def single_blog(request,slug):
    data = Blog.objects.get(slug=slug)
    # return render(request,'blog/single-blog.html', {'blog' : data})
    blog=Blog.objects.get(slug=slug)
    blog_comments = BlogComment.objects.filter(blog=blog, admin_verify=True, parent=None)
    blog_comments_count = BlogComment.objects.filter(blog=blog, admin_verify=True).count()
    return render(request,'blog/single-blog.html', {'blog' : blog, 'blog_comments':blog_comments, 'blog_comments_count':blog_comments_count})


def send_blog_comment(request):
    data = json.loads(request.body)
    # print(data.get('parent'))
    print(request.user)
    # print(x)
    this_blog = Blog.objects.get(id=data.get('blogid'))

    new_comment = BlogComment(
        user=request.user,
        blog=this_blog,
        text= data.get('comment_text'),
        parent_id = data.get('parent')
    )
    new_comment.save()


    return JsonResponse({'status':'ok'})

blog/templates/blog/blog.html
{% extends 'shared/base.html' %}
{% block title %} blog {% endblock %}
{% load humanize %}
{% block content %}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container main-container">
    <div class="row mt-5 pt-5">

        <div class="col-lg-9 col-md-8 col-sm-12 col-12 mb-3">
            <div class="row">
                {% for blog in this_page %}
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 post-mad">
                    <div class="post-card">
                        <div class="post-thumbnail">
                            <a href="{% url 'blog:single-blog' slug=blog.slug %}">
                                <img src="{{ blog.img.url }}" alt="">
                            </a>
                            <span class="post-tag">{{ blog.publisher }}</span>
                        </div>
                        <div class="post-title">
                            <a href="{% url 'blog:single-blog' slug=blog.slug  %}">
                             {{ blog.title }}
                            </a>
                            <span class="post-date">
                                {{ blog.date }}
                            </span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-12 col-12 mb-3 sidebar sticky-sidebar">
            <div class="widget-posts dt-sn dt-sl mb-3 border-bottom rounded-0">
                <div class="title-sidebar dt-sl mb-3">
                    <h3>جدیدترین نوشته ها</h3>
                </div>
                <div class="content-sidebar dt-sl">
                    {% for blog in recent_blog %}
                    <div class="item">
                        <div class="item-inner">
                            <div class="item-thumb">
                                <a href="#" class="img-holder">
                                    <img style="width: 90px; border-radius: 5px; height: 58px;" src="{{ blog.img.url }}" alt="">
                                </a>
                            </div>
                            <p class="title">
                                <a href="#">{{ blog.title }}</a>
                            </p>
                            <div class="item-meta">
                                <span class="time">{{ blog.date }}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="pagination">
                {% if this_page.has_previous %}
                <a href="/blog/?page={{ this_page.paginator_page_number }}" class="prev"><i class="mdi mdi-chevron-double-right"></i></a>
                {% endif %}
                {% for page in paginator.page_range %}
                <a href="/blog/?page={{ page }}" {% if page == this_page.number %} class="active-page" {% endif %}>{{ page }}</a>
                {% endfor %}
                {% if this_page.has_next %}
                <a href="/blog/?page={{ this_page.next_page_number }}" class="next"><i class="mdi mdi-chevron-double-left"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}